# Generated by Django 3.2 on 2023-02-17 23:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('FIRSTAPPLICATION', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='user_data',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('Name', models.CharField(max_length=100)),
                ('Contact', models.CharField(max_length=250)),
                ('Address', models.CharField(max_length=250)),
            ],
        ),
    ]
